### ISSUE TITLE
Deploy with Docker doesn't work on Ubuntu 18.04

### ISSUE THREAD

**Issue by Benjarobbi** [tmiland/Invidious-Updater#12]
Hi there,

I'm trying to install Invidious with your script on my Ubuntu 18.04 machine.
I've chosen option 3) to deploy it with Docker. However, this doesn't work correctly. 

After a while, your script runs into an error:
https://pastebin.com/raw/ARK3dUpd

Maybe you can do something with this information. I'm unsure what to do next. I'd appreciate it if you'd find a solution. :(

**Comment by tmiland** [comment]
Hi, 

looks like you might have to update crystal to version Crystal 0.31.1.

What's the output of `crystal -v`?
