### ISSUE TITLE
redhat-lsb not installing on GCP Centos 7

### ISSUE THREAD

**Issue by pulketo** [tmiland/Invidious-Updater#13]
Attemping to run invidious_update.sh on Centos 7 without redhat-lsb, won't install.

sudo ./invidious_update.sh 

✗ Looks like redhat-lsb is not installed!

Do you want to download redhat-lsb? [y/n]? y

➜ Installing redhat-lsb on CentOS Linux release 7.7.1908 (Core)...
✗ Error: could not install redhat-lsb!
✔ Done

✗ Looks like redhat-lsb is not installed!

Do you want to download redhat-lsb? [y/n]? n

./invidious_update.sh: line 177: lsb_release: command not found
./invidious_update.sh: line 177: lsb_release: command not found
./invidious_update.sh: line 194: lsb_release: command not found
./invidious_update.sh: line 210: lsb_release: command not found
✗ Error: Sorry, your OS is not supported.
---------------
workaround, install it manually with yum

**Comment by tmiland** [comment]
Hello,

might be because you ran the script with sudo. 

Try again with `./invidious_update.sh` as root.

E.g `su root` then `./invidious_update.sh`

Or enter root password when prompted running `./invidious_update.sh`
