### ISSUE TITLE
ERROR: Service 'invidious' failed to build on Centos 7

### ISSUE THREAD

**Issue by pulketo** [tmiland/Invidious-Updater#14]
Welcome to the Invidious Update.sh script.

What do you want to do?

  1) Install Invidious          5) Run Database Maintenance 
  2) Update Invidious           6) Start, Stop or Restart   
  3) Deploy with Docker         7) Uninstall Invidious      
  4) Install Invidious service  8) Set up PostgreSQL Backup 
  9) Exit                                                   
 
Docker Status:
Invidious: ▲ stopped PostgreSQL: ▲ stopped 

Documentation for this script is available here: 
 ➜ https://github.com/tmiland/Invidious-Updater

Select an option [1-9]: 3

 ╔═══════════════════════════════════════════════════════════════════╗
 ║                        Invidious Update.sh                        ║
 ║               Automatic update script for Invidio.us              ║
 ║                      Maintained by @tmiland                       ║
 ║                          version: 1.4.1                           ║
 ╚═══════════════════════════════════════════════════════════════════╝

Deploy Invidious with Docker.

What do you want to do?
   1) Build and start cluster
   2) Start, Stop or Restart cluster
   3) Rebuild cluster
   4) Delete data and rebuild
   5) Install Docker CE

Select an option [1-5]: 1
   Build and start cluster? [y/n]: y
Creating network "invidious_default" with the default driver
Creating volume "invidious_postgresdata" with default driver
Building postgres
Step 1/6 : FROM postgres:10
10: Pulling from library/postgres
80369df48736: Pull complete
b18dd0a6efec: Pull complete
5c20c5b8227d: Pull complete
c5a7f905c8ec: Pull complete
5a3f55930dd8: Pull complete
ffc097878b09: Pull complete
3106d02490d4: Pull complete
88d1fc513b8f: Pull complete
f19250dffc5e: Pull complete
756351b7a443: Pull complete
0d24b08575ba: Pull complete
31babd3be108: Pull complete
16f2724dc303: Pull complete
69802daaa561: Pull complete
Digest: sha256:3263c8dad1b5aa6be80144786b18515910165ed771863d686c8b8fda30fea1ad
Status: Downloaded newer image for postgres:10
 ---> 9a05a2b9e69f
Step 2/6 : ENV POSTGRES_USER postgres
 ---> Running in 9becec36d96a
Removing intermediate container 9becec36d96a
 ---> 0a575e71e917
Step 3/6 : ADD ./config/sql /config/sql
 ---> 3c3a06301266
Step 4/6 : ADD ./docker/entrypoint.postgres.sh /entrypoint.sh
 ---> 0e8f0fb1779e
Step 5/6 : ENTRYPOINT [ "/entrypoint.sh" ]
 ---> Running in 0081a465be2a
Removing intermediate container 0081a465be2a
 ---> f030860964cb
Step 6/6 : CMD [ "postgres" ]
 ---> Running in ddab400ac4db
Removing intermediate container ddab400ac4db
 ---> b3ac904397d4
Successfully built b3ac904397d4
Successfully tagged invidious_postgres:latest
WARNING: Image for service postgres was built because it did not already exist. To rebuild this image you must use `docker-compose build` or `docker-compose up --build`.
Building invidious
Step 1/20 : FROM alpine:edge AS builder
edge: Pulling from library/alpine
8c15e203d0eb: Pull complete
Digest: sha256:2f0fcd44f200bb1c0ddaed7370f042e66df1b7106c081285ad894e2fb9ba5bd2
Status: Downloaded newer image for alpine:edge
 ---> 60d63d8e1431
Step 2/20 : RUN apk add --no-cache crystal shards libc-dev     yaml-dev libxml2-dev sqlite-dev zlib-dev openssl-dev     sqlite-static zlib-static openssl-libs-static
 ---> Running in 0434ffd68c7a
fetch http://dl-cdn.alpinelinux.org/alpine/edge/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/edge/community/x86_64/APKINDEX.tar.gz
(1/57) Installing gc (8.0.4-r0)
(2/57) Installing libgcc (9.2.0-r2)
(3/57) Installing libstdc++ (9.2.0-r2)
(4/57) Installing libgc++ (8.0.4-r0)
(5/57) Installing pkgconf (1.6.3-r0)
(6/57) Installing gc-dev (8.0.4-r0)
(7/57) Installing libatomic_ops (7.6.10-r1)
(8/57) Installing libbz2 (1.0.8-r1)
(9/57) Installing expat (2.2.9-r0)
(10/57) Installing libffi (3.2.1-r6)
(11/57) Installing gdbm (1.13-r1)
(12/57) Installing xz-libs (5.2.4-r0)
(13/57) Installing ncurses-terminfo-base (6.1_p20191019-r0)
(14/57) Installing ncurses-terminfo (6.1_p20191019-r0)
(15/57) Installing ncurses-libs (6.1_p20191019-r0)
(16/57) Installing readline (8.0.1-r0)
(17/57) Installing sqlite-libs (3.30.1-r0)
(18/57) Installing python3 (3.8.0-r0)
(19/57) Installing libevent (2.1.11-r0)
(20/57) Installing libevent-dev (2.1.11-r0)
(21/57) Installing libevent-static (2.1.11-r0)
(22/57) Installing binutils (2.33.1-r0)
(23/57) Installing gmp (6.1.2-r1)
(24/57) Installing isl (0.18-r0)
(25/57) Installing libgomp (9.2.0-r2)
(26/57) Installing libatomic (9.2.0-r2)
(27/57) Installing mpfr4 (4.0.2-r1)
(28/57) Installing mpc1 (1.1.0-r1)
(29/57) Installing gcc (9.2.0-r2)
(30/57) Installing libgmpxx (6.1.2-r1)
(31/57) Installing gmp-dev (6.1.2-r1)
(32/57) Installing libpcre16 (8.43-r0)
(33/57) Installing libpcre32 (8.43-r0)
(34/57) Installing pcre (8.43-r0)
(35/57) Installing libpcrecpp (8.43-r0)
(36/57) Installing pcre-dev (8.43-r0)
(37/57) Installing llvm5-libs (5.0.2-r2)
(38/57) Installing crystal (0.31.1-r1)
(39/57) Installing musl-dev (1.1.24-r0)
(40/57) Installing libc-dev (0.7.1-r0)
(41/57) Installing zlib-dev (1.2.11-r3)
(42/57) Installing xz-dev (5.2.4-r0)
(43/57) Installing libxml2 (2.9.10-r0)
(44/57) Installing libxml2-dev (2.9.10-r0)
(45/57) Installing openssl-dev (1.1.1d-r2)
(46/57) Installing openssl-libs-static (1.1.1d-r2)
(47/57) Installing ca-certificates (20190108-r0)
(48/57) Installing nghttp2-libs (1.39.2-r2)
(49/57) Installing libcurl (7.67.0-r0)
(50/57) Installing pcre2 (10.33-r0)
(51/57) Installing git (2.24.0-r0)
(52/57) Installing yaml (0.2.2-r1)
(53/57) Installing shards (0.9.0-r1)
(54/57) Installing sqlite-dev (3.30.1-r0)
(55/57) Installing sqlite-static (3.30.1-r0)
(56/57) Installing yaml-dev (0.2.2-r1)
(57/57) Installing zlib-static (1.2.11-r3)
Executing busybox-1.31.1-r0.trigger
Executing ca-certificates-20190108-r0.trigger
OK: 290 MiB in 71 packages
Removing intermediate container 0434ffd68c7a
 ---> f7c8752a1751
Step 3/20 : WORKDIR /invidious
 ---> Running in 2ff490f1e27f
Removing intermediate container 2ff490f1e27f
 ---> 0a746fab55ea
Step 4/20 : COPY ./shard.yml ./shard.yml
 ---> c99ce4c8b1f8
Step 5/20 : RUN shards update && shards install
 ---> Running in fcbbf72ca8cc
Resolving dependencies
Fetching https://github.com/will/crystal-pg.git
Fetching https://github.com/crystal-lang/crystal-db.git
Fetching https://github.com/crystal-lang/crystal-sqlite3.git
Fetching https://github.com/kemalcr/kemal.git
Fetching https://github.com/luislavena/radix.git
Fetching https://github.com/jeromegn/kilt.git
Fetching https://github.com/crystal-loot/exception_page.git
Fetching https://github.com/ysbaddaden/pool.git
Fetching https://github.com/omarroth/protodec.git
Installing pg (0.19.0)
Installing sqlite3 (0.14.0)
Installing kemal (0.26.0)
Installing pool (0.2.3)
Installing protodec (0.1.2)
Installing radix (0.3.9)
Installing exception_page (0.1.2)
Installing db (0.7.0)
Installing kilt (0.4.0)
Writing shard.lock
Resolving dependencies
Fetching https://github.com/will/crystal-pg.git
Fetching https://github.com/crystal-lang/crystal-db.git
Fetching https://github.com/crystal-lang/crystal-sqlite3.git
Fetching https://github.com/kemalcr/kemal.git
Fetching https://github.com/luislavena/radix.git
Fetching https://github.com/jeromegn/kilt.git
Fetching https://github.com/crystal-loot/exception_page.git
Fetching https://github.com/ysbaddaden/pool.git
Fetching https://github.com/omarroth/protodec.git
Using pg (0.19.0)
Using sqlite3 (0.14.0)
Using kemal (0.26.0)
Using pool (0.2.3)
Using protodec (0.1.2)
Using radix (0.3.9)
Using exception_page (0.1.2)
Using db (0.7.0)
Using kilt (0.4.0)
Writing shard.lock
Removing intermediate container fcbbf72ca8cc
 ---> cdd5e8ca18aa
Step 6/20 : COPY ./src/ ./src/
 ---> a417c5d674fd
Step 7/20 : COPY ./.git/ ./.git/
 ---> ddb90d52ef04
Step 8/20 : RUN crystal build --static --release --warnings all --error-on-warnings     -Dmusl     ./src/invidious.cr
 ---> Running in 14b8d6e40d48

**Invalid memory access (signal 11) at address 0x7f715c4428f8
[0x56050030fa36] ???
[0x56050025e7f9] __crystal_sigfault_handler +457
[0x7f7188b1528f] ???
ERROR: Service 'invidious' failed to build: The command '/bin/sh -c crystal build --static --release --warnings all --error-on-warnings     -Dmusl     ./src/invidious.cr' returned a non-zero code: 11
✔ Deployment done.**

**Comment by tmiland** [comment]
That's an issue with Invidious Docker, no the script per se. 

Please report here: https://github.com/omarroth/invidious/issues/new

Thanks.
