### ISSUE TITLE
Updater script not supported on Linux Mint

### ISSUE THREAD

**Issue by tdeeb** [tmiland/Invidious-Updater#15]
**Describe the bug**
The updater script doesn't run on Linux Mint. It says the OS is unsupported.

**To Reproduce**
1. Try to run the script on a Linux Mint machine.

**Expected behavior**
The updater should run on Linux Mint under the Debian/Ubuntu code path, as Mint is a derivative of Ubuntu.

**Desktop (please complete the following information):**
 - OS: Linux Mint

**Additional context**
"LinuxMint" is the DISTRIB_ID of Linux Mint in **lsb-release**, and it uses `apt` as the package manager.

All code paths looking for the distro will need to be updated to account for it ([here](https://github.com/tmiland/Invidious-Updater/blob/master/invidious_update.sh#L122), [here](https://github.com/tmiland/Invidious-Updater/blob/master/invidious_update.sh#L178), [here](https://github.com/tmiland/Invidious-Updater/blob/master/invidious_update.sh#L420), and [here](https://github.com/tmiland/Invidious-Updater/blob/master/invidious_update.sh#L1827) just to name a few).

**Comment by tmiland** [comment]
Hi,

Linux Mint has not been tested.

Please check out latest [master](https://github.com/tmiland/Invidious-Updater/commit/5536e3221c914a34840c6e9a1128f392739a5352) and report back if everything works or not, and I'll push an update. :+1: 

Thanks.

**Comment by tdeeb** [comment]
Hi @tmiland, thanks for addressing this so quickly! I tested the script and managed to get a local Invidious instance running on my Mint installation! Thanks a lot!

**Comment by tmiland** [comment]
> Hi @tmiland, thanks for addressing this so quickly! I tested the script and managed to get a local Invidious instance running on my Mint installation! Thanks a lot!

That's great! Enjoy :+1:
