### ISSUE TITLE
[Feature Request] Ability to install older branches/releases

### ISSUE THREAD

**Issue by m4teh** [tmiland/Invidious-Updater#17]
Latest Invidious release/master has bugs preventing subscription updating. Had to manually downgrade.
A third option under install menu with a list of recent branches would be excellent!

**Comment by tmiland** [comment]
Hi, great idea. 

Have been looking at this now, and will not implement this at the moment.

It is expected though that before updating, check to see if there are any bug reports.

Might have a look at it at a later time.

Thanks.

**Comment by tmiland** [comment]
Closing.
