### ISSUE TITLE
Problem installing on Debian 10

### ISSUE THREAD

**Issue by haizrul** [tmiland/Invidious-Updater#18]
Hi i tried installing invidious script using Invidious-Updater. My server running a Debian 10 on DigitalOcean as recommended. Fresh install. See screenshot below.

![Screenshot](https://user-images.githubusercontent.com/8771582/70306636-55866280-1842-11ea-9156-19a0489b90ca.png)

**Comment by tmiland** [comment]
Hi, 

could you post the content of `/etc/apt/sources.list`?

Not sure why, but you have `/ubuntu buster` which is a mix of ubuntu and debian. 

Correct sources for Debian 10 would be:

```
deb http://deb.debian.org/debian buster main
deb http://deb.debian.org/debian buster-updates main
deb http://security.debian.org/debian-security buster/updates main
```

Then run `apt update` and try again.

**Comment by haizrul** [comment]
> could you post the content of /etc/apt/sources.list?

## Note, this file is written by cloud-init on first boot of an instance
## modifications made here will not survive a re-bundle.
## if you wish to make changes you can:
## a.) add 'apt_preserve_sources_list: true' to /etc/cloud/cloud.cfg
##     or do the same in user-data
## b.) add sources in /etc/apt/sources.list.d
## c.) make changes to template file /etc/cloud/templates/sources.list.tmpl

# See http://help.ubuntu.com/community/UpgradeNotes for how to upgrade to
# newer versions of the distribution.
deb http://mirrors.digitalocean.com/ubuntu/ buster main restricted
deb-src http://mirrors.digitalocean.com/ubuntu/ buster main restricted

## Major bug fix updates produced after the final release of the
## distribution.
deb http://mirrors.digitalocean.com/ubuntu/ buster-updates main restricted
deb-src http://mirrors.digitalocean.com/ubuntu/ buster-updates main restricted

## N.B. software from this repository is ENTIRELY UNSUPPORTED by the Ubuntu
## team. Also, please note that software in universe WILL NOT receive any
## review or updates from the Ubuntu security team.
deb http://mirrors.digitalocean.com/ubuntu/ buster universe
deb-src http://mirrors.digitalocean.com/ubuntu/ buster universe
deb http://mirrors.digitalocean.com/ubuntu/ buster-updates universe
deb-src http://mirrors.digitalocean.com/ubuntu/ buster-updates universe

## N.B. software from this repository is ENTIRELY UNSUPPORTED by the Ubuntu 
## team, and may not be under a free licence. Please satisfy yourself as to 
## your rights to use the software. Also, please note that software in 
## multiverse WILL NOT receive any review or updates from the Ubuntu
## security team.
deb http://mirrors.digitalocean.com/ubuntu/ buster multiverse
deb-src http://mirrors.digitalocean.com/ubuntu/ buster multiverse
deb http://mirrors.digitalocean.com/ubuntu/ buster-updates multiverse
deb-src http://mirrors.digitalocean.com/ubuntu/ buster-updates multiverse

## N.B. software from this repository may not have been tested as
## extensively as that contained in the main release, although it includes
## newer versions of some applications which may provide useful features.
## Also, please note that software in backports WILL NOT receive any review
## or updates from the Ubuntu security team.
deb http://mirrors.digitalocean.com/ubuntu/ buster-backports main restricted universe multiverse
deb-src http://mirrors.digitalocean.com/ubuntu/ buster-backports main restricted universe multiverse

deb http://security.ubuntu.com/ubuntu buster-security main restricted
deb-src http://security.ubuntu.com/ubuntu buster-security main restricted
deb http://security.ubuntu.com/ubuntu buster-security universe
deb-src http://security.ubuntu.com/ubuntu buster-security universe
deb http://security.ubuntu.com/ubuntu buster-security multiverse
deb-src http://security.ubuntu.com/ubuntu buster-security multiverse

## Uncomment the following two lines to add software from Canonical's
## 'partner' repository.
## This software is not part of Ubuntu, but is offered by Canonical and the
## respective vendors as a service to Ubuntu users.
# deb http://archive.canonical.com/ubuntu buster partner
# deb-src http://archive.canonical.com/ubuntu buster partner

**Comment by tmiland** [comment]
> > could you post the content of /etc/apt/sources.list?
> 
> https://pastebin.com/nRa6aaWp

Have a look here: https://www.digitalocean.com/community/questions/why-does-fresh-debian-10-image-fail-apt-update

**Comment by haizrul** [comment]
Ok my bad. I rebuild debian 10 from ubuntu. Thats why its not working. After creating new debian 10 droplet, its working fine. Thank you for your help.

**Comment by tmiland** [comment]
> Ok my bad. I rebuild debian 10 from ubuntu. Thats why its not working. After creating new debian 10 droplet, its working fine. Thank you for your help.

No worries. Glad you got it working :smile:
