### ISSUE TITLE
help: installed on ubuntu vps but can't access it

### ISSUE THREAD

**Issue by msiqu** [tmiland/Invidious-Updater#19]
Hi, I installed invidious using this updater on a vps. I'm trying to access that installation using http://[vps-ip]:3000 but I can't.

Running the installer I can see that:

> Services running:
> Invidious: ● active 
> PostgreSQL: ● active

How else can I check the installation?

**Comment by tmiland** [comment]
Hi, 

try to add `host_binding: [vps-ip]` to config yml

`sudo -i -u invidious nano /home/invidious/invidious/config/config.yml`

Then do `systemctl restart invidious`
