### ISSUE TITLE
Entering anything else than y or n exits script

### ISSUE THREAD

**Issue by Perflyst** [tmiland/Invidious-Updater#2]
If you just press enter or enter anything else than `y` or `n` on this question `"Is that correct? Enter y or n:"` the script stops.

**Comment by tmiland** [comment]
That is correct. 

`    read -p "Is that correct? Enter y or n: " confirm && [[ $confirm == [yY] || $confirm == [yY][eE][sS] ]] || exit 1`

If you've entered the correct answer, Y must be entered to confirm.

**Comment by Perflyst** [comment]
Why do you do it like this? I mean completely exiting the script just because you type another symbole accidently....

**Comment by tmiland** [comment]
> Why do you do it like this? I mean completely exiting the script just because you type another symbole accidently....

Well, i expect the user to enter the correct answer. 

I recently removed a lot of user input prompt's to make it more streamlined.

So if the user can get through the setup (which is quite important), the rest will take care of itself. 

How else would you want it? Be as specific as possible.

Thanks.

**Comment by tmiland** [comment]
Lots of changes done in https://github.com/tmiland/Invidious-Updater/commit/0b3b6ee11a9ecada9b1e50b3b44fb45408cdc218

Closing. Reopen if it's still an issue.
