### ISSUE TITLE
gpg dependency

### ISSUE THREAD

**Issue by p-rintz** [tmiland/Invidious-Updater#20]
**Describe the bug**
When installing on a minimal install without gnupg1/2, the install will fail, as the dependency isnt checked or installed.

**To Reproduce**
1. Use minimal install without gnupg2 installed.
2. Use script.
3. Fail, as the additional repositories cant be added.

**Expected behavior**
Either install the dependency,prompt the user to or mention it in the readme.

**Desktop (please complete the following information):**
 - OS: Debian 10 - minimal install

Secondary issue is that it all fails very quietly. At the end, the script will say that the install was successful, even though it was not.

**Comment by tmiland** [comment]
Thanks for reporting. Should be fixed in master branch.
