### ISSUE TITLE
Support for Arch Linux

### ISSUE THREAD

**Issue by ryeenii** [tmiland/Invidious-Updater#21]
**Is your feature request related to a problem? Please describe.**
I've been wanting to make an unique instance on one of my ends using Arch Linux, and once i figured out that the system wasn't supported in the shell script it was slightly disappointing as it can be used as a beefy server distro (even if it's main targets are client-wise).

**Describe the solution you'd like**
Add a compatibility layer to `pacman` and parse the OS information using `/etc/os_release` instead. There _is_ an Required Packages for Arch Linux on the official Invidious README so it should help on the development of such feature. 

**Describe alternatives you've considered**
While i could compile the app by myself using the given instructions on the Invidious' README, I Ended up realizing on how it was not going to be that worth it as it's very difficult to keep up with the updates without something like a tool. That's where i found out this branch and tried it myself, only to realize that such compatibility wasn't even around.

**Additional context**
![image](https://user-images.githubusercontent.com/56133320/74203623-04825880-4c4f-11ea-9409-c21f9f4927ce.png)

**Comment by tmiland** [comment]
Hi,

Try  https://github.com/tmiland/Invidious-Updater/releases/tag/v1.4.6

Let me know if you experience any issues. :+1:

**Comment by ryeenii** [comment]
Thank you so much! It's working like a charm.
