### ISSUE TITLE
Systemctl daemon needs to be reloaded after an update

### ISSUE THREAD

**Issue by TheFrenchGhosty** [tmiland/Invidious-Updater#23]
**Describe the bug**
When updating Invidious, a warning will quickly appear saying that because the service file has changed "systemctl daemon-reload" is needed. It would be nice if the script did it itself.

**Additional context**
Bare metal install (not docker).

**Comment by tmiland** [comment]
The service file is not touched while updating Invidious. 

So it might just be that the file has changed, and "systemctl daemon-reload" is needed, so it wouldn't make sense to have the script do "systemctl daemon-reload".
