### ISSUE TITLE
the script crash when running installation on a machine with less than 2GB of ram

### ISSUE THREAD

**Issue by sebas891** [tmiland/Invidious-Updater#27]
**Describe the bug**
I'm trying to install invidious (option 1 in the menu) of invidious-updater on a freshly create virtual machine with Debian 10 on 32bits with 512GB of ram and 2 cores.  The installation fails without information about the cause. This is the exact same error message as of bug #25 the submitter didn't state how much ram he's having.

```
...
Using exception_page (0.1.4)
Writing shard.lock
Showing last frame. Use --error-trace for full trace.

In lib/pg/src/pq/connection.cr:170:20

 170 | rescue e : Errno
                  ^----
Error: Errno is not a subclass of Exception
```
**Expected behavior**
I would expect to be notified by the upstream project on how much ram is needed to build the software. I submitted an issue there. https://github.com/omarroth/invidious/issues/1152

I think it would be very nice to warn the user that it's not possible to build the software on a machine with less than 2 GB of ram. That could be somewhere in the menu of options in "red" if the system has less than 2GB of ram. I don't have  PR for you on this, I don't know how to make that nice menu you did.

**Additional context**

I did try to build invidious with 512GB, 750GB, 1300GB without success. I was following this method. https://github.com/omarroth/invidious#setup-invidious

**Comment by ChaseHall** [comment]
I am running this on a fresh LXC in Proxmox, giving it 4GBs of RAM; Still also get this error, unsure if it's because of the LXC or not. [(Screenshot)](https://chase.pics/u/hwiHjCV.png)

**Comment by sebas891** [comment]
@ChaseHall I suspect it's not a bug about the install script, but the compilation of invidious.  Did you try to do this 

```
$ sudo -i -u invidious
 $ cd invidious
$ shards update && shards install
$ crystal build src/invidious.cr --release
# test compiled binary
$ ./invidious # stop with ctrl c
$ exit

```
To see if you get the same error message?  For me I get this error message, see bug https://github.com/omarroth/invidious/issues/1153

**Comment by ChaseHall** [comment]
@sebas891 I was able to get it working using the steps on the Invidious GitHub, however I had to change the way SQL was accepting commands. [Here's my commands I had to run.](https://pastebin.com/raw/umU1nTJj)

**Comment by sebas891** [comment]
@ChaseHall cool, are you running on 32bits or 64 bits?

**Comment by ChaseHall** [comment]
@sebas891 64 Bit.

**Comment by sebas891** [comment]
@ChaseHall thanks for the details. I suspect I'm having problem because of the 32bits architecture.

**Comment by gripped** [comment]
I had this error trying to build the release version. 
On a aws t3.micro instance, Ubuntu 18.04, 2G swap file. And again with Centos (aws), And again on a local xubuntu 18.4 KVM with 8G of ram.
Using git master instead of release worked.

**Comment by GauthierPLM** [comment]
When using the master version (instead of release), I encountered the memory limit: the build process was killed by the kernel because it used too much memory (the build process requires 1.4GB of memory).

Upgrading my droplet to 2GB fixed the issue. However, the errno error does not seem to be related to the memory limit (when a process uses too much memory, it is killed by the kernel, it's not a crystal error).

**Comment by plasticmacaroni** [comment]
I fixed this issue by adding a swapfile to my instance. Of course, drive space may be another issue.

If you're not sure what that means, here are fairly simple instructions on setting up a 4GB swapfile on Ubuntu: https://tecadmin.net/enable-swap-on-ubuntu/

**Comment by tmiland** [comment]
Option to add swap space added in 1.4.8

Closing. :+1:
