### ISSUE TITLE
Check if Invidious is already installed

### ISSUE THREAD

**Issue by Perflyst** [tmiland/Invidious-Updater#3]
At the moment you can just select `Install` again and the script does not warn you about any active installation. This can kill the current setup.

**Comment by tmiland** [comment]
> At the moment you can just select `Install` again and the script does not warn you about any active installation. This can kill the current setup.

Well, it is a one time installation script, not meant for re-install.

Have plans to add uninstall option.

I'll have a look at implementing a warning. 

Thanks

**Comment by tmiland** [comment]
Should be fixed in latest version [1.1.4](https://github.com/tmiland/Invidious-Updater/commit/c924581b2783acbfcdfd43efc44b225d96fb40dd#diff-ea1f78964b695fa47c45ca887e8a7089)
