### ISSUE TITLE
Fedora 32 install broken

### ISSUE THREAD

**Issue by Broeckelmann** [tmiland/Invidious-Updater#30]
**To Reproduce**
Try to install on Fedora 32 with option 1, then 1, then y

**Expected behavior**
That It just works, its still a very nice project :+1: 

**Desktop (please complete the following information):**
 - OS: Fedora 
 - Browser: Chrome
 - Version 32

**Additional context**
Method arguments are broken, atleast on Fedora 32 it seems like. 
![Error Fedora 32 invidious install](https://user-images.githubusercontent.com/45721680/85075463-84509e80-b1be-11ea-9d95-6f50d5b4d815.png)

**Comment by aabbcdd99** [comment]
Same error here too. Trying to install invidious with Debian Buster (10).

_Linux debian-vps-amd64 #1 SMP Debian 4.19.118-2 (2020-04-29) x86_64 GNU/Linux_

```
Using pool (0.2.3)
Using protodec (0.1.3)
Using lsquic (0.1.9)
Warning: Zlib is deprecated, use Compress::Zlib
Warning: Zip is deprecated, use Compress::Zip
Showing last frame. Use --error-trace for full trace.

In lib/pg/src/pq/connection.cr:349:13

 349 | ctx.update(inner.to_unsafe, inner.bytesize.to_u32)
           ^-----
Error: wrong number of arguments for 'OpenSSL::Digest#update' (given 2, expected 1)

Overloads are:
 - OpenSSL::DigestBase#update(io : IO)
 - Digest::Base#update(data : Bytes)
 - Digest::Base#update(data)
✗ Invidious service installation failed...

```
Found this resource from Google:
https://forum.crystal-lang.org/t/postgresql-db-open-does-not-work-in-crystal-v-0-35/2236

Tried to update and install shards dependencies with this shard.yml: 
```
dependencies:
  pg:
    github: will/crystal-pg
    version: "~> 0.21.1"
  db:
    github: crystal-lang/crystal-db
    version: "~> 0.9.0"
```

Still got the same error. :-(

**Comment by tmiland** [comment]
> **To Reproduce**
> Steps to reproduce the behavior:
> Try to install on Fedora 32 with option 1, then 1, then y
> 
> **Expected behavior**
> That It just works, its still a very nice project +1
> 
> **Desktop (please complete the following information):**
> 
>     * OS: Fedora
> 
>     * Browser: Chrome
> 
>     * Version 32
> 
> 
> **Additional context**
> Method arguments are broken, atleast on Fedora 32 it seems like.


Hi, please see [Compatibility and Requirements](https://github.com/tmiland/Invidious-Updater#compatibility-and-requirements)

**Comment by aabbcdd99** [comment]
> > **To Reproduce**
> > Steps to reproduce the behavior:
> > Try to install on Fedora 32 with option 1, then 1, then y
> > **Expected behavior**
> > That It just works, its still a very nice project +1
> > **Desktop (please complete the following information):**
> > ```
> > * OS: Fedora
> > 
> > * Browser: Chrome
> > 
> > * Version 32
> > ```
> > 
> > 
> > **Additional context**
> > Method arguments are broken, atleast on Fedora 32 it seems like.
> 
> Hi, please see [Compatibility and Requirements](https://github.com/tmiland/Invidious-Updater#compatibility-and-requirements)

It says Debian 8 or later, and it failed with Debian 10.

**Comment by tmiland** [comment]
That is correct. I was quoting the first post. Your issue is not an error with the script.

**Comment by tmiland** [comment]
> **To Reproduce**
> Steps to reproduce the behavior:
> Try to install on Fedora 32 with option 1, then 1, then y
> 
Also, install with option 2 (Master), there hasn't been a release since [Nov 19, 2019](https://github.com/omarroth/invidious/releases/tag/0.20.1). It might work.

**Comment by tmiland** [comment]
> Same error here too. Trying to install invidious with Debian Buster (10).
> 
> _Linux debian-vps-amd64 #1 SMP Debian 4.19.118-2 (2020-04-29) x86_64 GNU/Linux_
> 
> ```
> Using pool (0.2.3)
> Using protodec (0.1.3)
> Using lsquic (0.1.9)
> Warning: Zlib is deprecated, use Compress::Zlib
> Warning: Zip is deprecated, use Compress::Zip
> Showing last frame. Use --error-trace for full trace.
> 
> In lib/pg/src/pq/connection.cr:349:13
> 
>  349 | ctx.update(inner.to_unsafe, inner.bytesize.to_u32)
>            ^-----
> Error: wrong number of arguments for 'OpenSSL::Digest#update' (given 2, expected 1)
> 
> Overloads are:
>  - OpenSSL::DigestBase#update(io : IO)
>  - Digest::Base#update(data : Bytes)
>  - Digest::Base#update(data)
> ✗ Invidious service installation failed...
> ```
> 
> Found this resource from Google:
> https://forum.crystal-lang.org/t/postgresql-db-open-does-not-work-in-crystal-v-0-35/2236
> 
> Tried to update and install shards dependencies with this shard.yml:
> 
> ```
> dependencies:
>   pg:
>     github: will/crystal-pg
>     version: "~> 0.21.1"
>   db:
>     github: crystal-lang/crystal-db
>     version: "~> 0.9.0"
> ```
> 
> Still got the same error. :-(

Installed just now on Deban 10 with option 2 (Master)

![Screenshot from 2020-06-19 09-21-57](https://user-images.githubusercontent.com/1203834/85107629-d1079a00-b1fd-11ea-972f-28ca7ed6102c.png)

**Comment by aabbcdd99** [comment]
Awesome, the option (master) worked fine, now the script goes forward and it works. Thanks for the handy script.

**Comment by tmiland** [comment]
> Awesome, the option (master) worked fine, now the script goes forward and it works. Thanks for the handy script.

That's great! You're welcome.

**Comment by tmiland** [comment]
Also works on Fedora 29.

![Screenshot from 2020-06-19 10-35-09](https://user-images.githubusercontent.com/1203834/85114063-d79b0f00-b207-11ea-8b2f-8e244289dcd0.png)

**Comment by Broeckelmann** [comment]
Try'd around, but can't get it to work it just isn't supported for the moment hopefully. Thanks for the help :+1: .
