### ISSUE TITLE
Docker Choose diffrent port for compose

### ISSUE THREAD

**Issue by ckorder** [tmiland/Invidious-Updater#36]
It would be very nice `if the taken port from the compose docker configuration file could be changed from within the script` otherwise **port 3000** f. e. is taken as well taken by other services like **searx**

**Comment by tmiland** [comment]
Hello,

change `port: 3000` in `config.yml` for now. 

I'll have a look later. :+1:

**Comment by tmiland** [comment]
Okay, try this 07d7e03 :+1:

**Comment by ckorder** [comment]
I do. Thank you!
