### ISSUE TITLE
Permit to update through cron

### ISSUE THREAD

**Issue by vinyll** [tmiland/Invidious-Updater#37]
Updating through a crontab is not currently possible as the script depends on the prompt interaction from a human.

It would be ideal to run something like `./inviduous-updater.sh --option=update` without a prompt so that it can be called from a cron task.

**Comment by tmiland** [comment]
Cron update option added to Master.

Not yet tested while there is an update available. (But should work)

Call from cron with: `invidious_update -c`

Will do a release after testing is ok. :+1:

**Comment by tmiland** [comment]
Added to release [v1.5.1](https://github.com/tmiland/Invidious-Updater/releases/tag/v1.5.1)
