### ISSUE TITLE
Invidious User does not need sudo permissions?

### ISSUE THREAD

**Issue by Perflyst** [tmiland/Invidious-Updater#4]
The script adds the user invidious with sudo permissions. I don't see any use case why it should need sudo permission.

**Comment by tmiland** [comment]
> The script adds the user invidious with sudo permissions. I don't see any use case why it should need sudo permission.

To have permission to the user folder in `USER_DIR="/home/invidious"`.

This is also the user Invidious will run as. Per https://github.com/omarroth/invidious/blob/master/invidious.service

`User=invidious
Group=invidious`

**Comment by Perflyst** [comment]
The user `invidious` does not need sudo permissions to have access to `/home/invidious`. Also it does not need sudo to run invidious. Sure you need to start the service itself with sudo permissions but this shouldnt be done with the `invidious` user.

**Comment by tmiland** [comment]
I recently added; https://github.com/tmiland/Invidious-Updater/blob/d27ccb3a9ff2da8c78384b89a0ed8746d5719e6a/invidious_update.sh#L129
To avoid permission issues during git pulls.

Main reason i added the user `invidious` to sudoers, was that i got permission denied with the user `postgres` when running the maintenance part.

> sudo -u postgres psql invidious -c "TRUNCATE TABLE videos;" 
> could not change directory to "/home/invidious/invidious": Permission denied

Hence;  https://github.com/tmiland/Invidious-Updater/blob/d27ccb3a9ff2da8c78384b89a0ed8746d5719e6a/invidious_update.sh#L513
And; https://github.com/tmiland/Invidious-Updater/blob/d27ccb3a9ff2da8c78384b89a0ed8746d5719e6a/invidious_update.sh#L514


Just run `sudo deluser invidious sudo` if you're not going to use maintenance.

**Comment by tmiland** [comment]
Should be fixed in https://github.com/tmiland/Invidious-Updater/commit/0b3b6ee11a9ecada9b1e50b3b44fb45408cdc218
