### ISSUE TITLE
App listening only on IPv6, not IPv4

### ISSUE THREAD

**Issue by eave** [tmiland/Invidious-Updater#45]
I've completed the installation on a VPS with a clean Debian 10 OS install.  I chose #1 on the Invidious-Updater installation prompt for a clean install, without any customization.  In my terminal, I see that both the Invidious and PostgreSQL services are running without issue--but when I navigate to my VPS' IP in my browser, the application does not come up.

I ran netstat, and found that my app is only listening on IPv6, and not on IPv4 (screenshot attached).  Any guidance to get it to listen on IPv4?  I appreciate the help!

![netstat_edited](https://user-images.githubusercontent.com/6742336/106105792-67d3f780-60f9-11eb-87e0-4be474962cd3.png)

**Comment by tmiland** [comment]
Hello,

try `sudo -i -u invidious nano /home/invidious/invidious/config/config.yml` then add `force_resolve: ipv4` on a new line.

**Comment by eave** [comment]
Hi @tmiland --thanks for helping troubleshoot!  I've added this line (please see attached) and restarted both the VPS and the service itself, but it still doesn't seem to be listening on IPv4--the netstat results are the same.

Do you have any other ideas?  Thanks again for the help!

![Screenshot_20210128_073110](https://user-images.githubusercontent.com/6742336/106161062-5d3a5200-613b-11eb-86b2-d988d73bf2f3.png)

**Comment by tmiland** [comment]
Hi,

i assume you have port 3000 forwarded in your firewall? 

Also try to add:
`port: 3000`
And:
`host_binding: xx.xx.xx.xx` where `xx.xx.xx.xx` is your local IP.

Then it should be accessible at http://your_public_ip:3000

If this still fails, then use option 7 to uninstall, and set it up again with advanced options.

**Comment by tmiland** [comment]
Feel free to re-open if this is still an issue.

**Comment by eave** [comment]
Hi @tmiland --thanks for the help!  I wasn't able to resolve this, so I've retried with a few different OSes on my VPS.  I currently have Deployed Invidious with Docker on Fedora 33 x64.  Both the service and database are up and running, according to the script--but again, I'm having trouble finding it through the browser.  Should it just be http://my.vps.ip.address:3000 ?

Thanks again!

**Comment by tmiland** [comment]
Hi again, my pleasure. :smile: 

yes, it should be, if you have the port open in your firewall and the port forwarded correctly in Docker.

**Comment by eave** [comment]
Hi @tmiland -- thanks!  I believe I have a) the correct port assigned in Docker, and b) that port mapped correctly, according to netstat (screenshots attached).  Does anything seem out of the ordinary to you?  Again, I really appreciate all of your help.
![2021-02-01_23-22_1_](https://user-images.githubusercontent.com/6742336/106568052-9aaa3100-64e7-11eb-9a07-6e36d11ce15a.png)
![2021-02-01_23-22_12](https://user-images.githubusercontent.com/6742336/106568059-9e3db800-64e7-11eb-8e2e-9852f466bd93.png)

**Comment by tmiland** [comment]
Hello again,

looks correct.

Now the only question remaining; are the port opened in your firewall?

**Comment by eave** [comment]
Here are my current rules, according to iptables--don't think anything should be blocked?
![2021-02-02_00-13](https://user-images.githubusercontent.com/6742336/106571142-a4359800-64eb-11eb-9f26-0d90d7f77f1c.png)

**Comment by tmiland** [comment]
Hmm,

try this: `firewall-cmd --permanent --add-port 3000/tcp` then `systemctl restart firewalld` and see if that helps. 

From [Opening a port - Using firewalld on Fedora](https://docs.fedoraproject.org/en-US/quick-docs/firewalld/#opening-ports-firewalld-fedora)

**Comment by eave** [comment]
Hi @tmiland --hmm, still seems to be failing.  I'll play around with this and try to figure something out.  Looking forward to continuing to use and suport the project!!
