### ISSUE TITLE
Use new apt / rpm repository

### ISSUE THREAD

**Issue by Perflyst** [tmiland/Invidious-Updater#46]
Crystal changed their apt / rpm repo, the old one is already EOL.

More information:

https://crystal-lang.org/2020/08/24/announcing-new-apt-and-rpm-repositories.html

**Comment by tmiland** [comment]
Test on Debian 10 resulted in error with updated repo.

```bash
Showing last frame. Use --error-trace for full trace.

In src/invidious/helpers/proxy.cr:76:7

 76 | @socket = nil
      ^
Error: instance variable @socket of HTTPClient was inferred to be Nil, but Nil alone provides no information

```

```bash
crystal -v
Crystal 0.36.0 [1e6f96aef] (2021-01-26)

LLVM: 10.0.0
Default target: x86_64-unknown-linux-gnu
```

**Comment by tmiland** [comment]
Installed successfully on Fedora. 🤔

```bash
crystal -v
Crystal 0.35.1 [5999ae29b] (2020-06-19)

LLVM: 8.0.0
Default target: x86_64-unknown-linux-gnu
```

**Comment by Perflyst** [comment]
Which version on Debian 10 is installed? Invidious on crystal 0.36.0 requires a patch: https://patch-diff.githubusercontent.com/raw/iv-org/invidious/pull/1734.patch

**Comment by tmiland** [comment]
It's the stable channel on debian 10, which is Crystal 0.36.0.
