### ISSUE TITLE
Invidious' master requires Crystal 0.36.0

### ISSUE THREAD

**Issue by GauthierPLM** [tmiland/Invidious-Updater#48]
Following iv-org/invidious#1734, Invidious won't build with crystal 0.35.1. Invidious Updated should install crystal 0.36.0 instead of 0.35.1 if possible.

**Comment by tmiland** [comment]
I was waiting for that pull request to be merged. 

It will be fixed with the new repos mentioned in https://github.com/tmiland/Invidious-Updater/issues/46
