### ISSUE TITLE
Let's Encrypt integration if domain is configured

### ISSUE THREAD

**Issue by GauthierPLM** [tmiland/Invidious-Updater#51]
**Is your feature request related to a problem? Please describe.**
Issuing Let's Encrypt certificates is easy and certbot (or alternative tools) are widely available to automatically sign certificates.

it would be nice if certificates could be issued using Invidious Updater (the script would call certbot as it does with Nginx auto installer), and if the certificate were installed automatically, either by configuring Invidious directly, or using the VHost (which already uses Let's Encrypt certificate in its default configuration).

**Describe the solution you'd like**
During the install process, if a domain is provided, the user should have the possibility to install a certificate for the domain.

If the user decides to install Nginx Vhost, the configuration set in Invidious should be updated to transfer the certificate handling to Nginx (remove SSL configuration ? I am not knowledgeable enough to be sure about this).

**Describe alternatives you've considered**
Installing the certificate manually might be a bit confusing for new users or people without high tech skills.

**Comment by tmiland** [comment]
Hello,

please test https://github.com/tmiland/Invidious-Updater/commit/a2cd6c111c5af9d8df05177be5743d177de6959c

Let me know if it works. :+1:

**Comment by GauthierPLM** [comment]
Hello,

When running the install (Ubuntu 20.04 on Digital Ocean droplet), I got the following failure:

```
--2021-02-05 14:36:28--  https://raw.githubusercontent.com/certbot/certbot/v1.9.0/certbot-auto
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.36.133
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.36.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 78696 (77K) [text/plain]
Saving to: ‘certbot-auto’

certbot-auto                  100%[=================================================>]  76.85K  --.-KB/s    in 0.001s

2021-02-05 14:36:28 (52.5 MB/s) - ‘certbot-auto’ saved [78696/78696]

Bootstrapping dependencies for Debian-based OSes... (you can skip this with --no-bootstrap)
Get:1 http://mirrors.digitalocean.com/ubuntu focal InRelease [265 kB]
Ign:2 https://dl.bintray.com/crystal/deb all InRelease
Hit:3 http://mirrors.digitalocean.com/ubuntu focal-updates InRelease
Get:4 https://dl.bintray.com/crystal/deb all Release [3611 B]
Hit:5 http://mirrors.digitalocean.com/ubuntu focal-backports InRelease
Get:6 http://security.ubuntu.com/ubuntu focal-security InRelease [109 kB]
Fetched 378 kB in 1s (615 kB/s)
Reading package lists... Done
Reading package lists... Done
Building dependency tree
Reading state information... Done
Note, selecting 'python-is-python2' instead of 'python'
Note, selecting 'python-dev-is-python2' instead of 'python-dev'
Package python-virtualenv is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'python-virtualenv' has no installation candidate
```

Also, I noticed that the question asking for an email to provide to Let's Encrypt miss spacing at the end of the sentence:
`Please enter your admin email for the domain [E.G: admin@invidious.domain.tld]`
It should be:
`Please enter your admin email for the domain [E.G: admin@invidious.domain.tld]: `

**Comment by tmiland** [comment]
> Hello,
> 
> When running the install (Ubuntu 20.04 on Digital Ocean droplet), I got the following failure:
> 
> ```
> --2021-02-05 14:36:28--  https://raw.githubusercontent.com/certbot/certbot/v1.9.0/certbot-auto
> Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.36.133
> Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.36.133|:443... connected.
> HTTP request sent, awaiting response... 200 OK
> Length: 78696 (77K) [text/plain]
> Saving to: ‘certbot-auto’
> 
> certbot-auto                  100%[=================================================>]  76.85K  --.-KB/s    in 0.001s
> 
> 2021-02-05 14:36:28 (52.5 MB/s) - ‘certbot-auto’ saved [78696/78696]
> 
> Bootstrapping dependencies for Debian-based OSes... (you can skip this with --no-bootstrap)
> Get:1 http://mirrors.digitalocean.com/ubuntu focal InRelease [265 kB]
> Ign:2 https://dl.bintray.com/crystal/deb all InRelease
> Hit:3 http://mirrors.digitalocean.com/ubuntu focal-updates InRelease
> Get:4 https://dl.bintray.com/crystal/deb all Release [3611 B]
> Hit:5 http://mirrors.digitalocean.com/ubuntu focal-backports InRelease
> Get:6 http://security.ubuntu.com/ubuntu focal-security InRelease [109 kB]
> Fetched 378 kB in 1s (615 kB/s)
> Reading package lists... Done
> Reading package lists... Done
> Building dependency tree
> Reading state information... Done
> Note, selecting 'python-is-python2' instead of 'python'
> Note, selecting 'python-dev-is-python2' instead of 'python-dev'
> Package python-virtualenv is not available, but is referred to by another package.
> This may mean that the package is missing, has been obsoleted, or
> is only available from another source
> 
> E: Package 'python-virtualenv' has no installation candidate
> ```
> 
> Also, I noticed that the question asking for an email to provide to Let's Encrypt miss spacing at the end of the sentence:
> `Please enter your admin email for the domain [E.G: admin@invidious.domain.tld]`
> It should be:
> `Please enter your admin email for the domain [E.G: admin@invidious.domain.tld]: `

Well, you need to install python and python-virtualenv. Once you have that working, it should work. :+1:

**Comment by GauthierPLM** [comment]
Even with the packages `python3` and `python3-virtualenv` installed, the script still tries to install `python-virtualenv`, which does not exists in Ubuntu 20.04 repositories.

**Comment by tmiland** [comment]
My guess is that you need python2.

`sudo apt install python2 virtualenv`

**Comment by GauthierPLM** [comment]
As I said, the script tries to install packages that simply do not exist in Ubuntu repositories, and does so every time. It is [hardcoded](https://github.com/certbot/certbot/blob/master/certbot-auto#L346) in the certbot-auto script: if the package is not explicitly installed, the script will try to install it (and fail as it does not exists).

**Comment by tmiland** [comment]
Okay, trying a different approach c3464d4

Let me know if it works. :+1:

**Comment by GauthierPLM** [comment]
Hello,

So I tried the script.
It seems that in case of error, the script still consider the install was successful:
I have the following error when installing the certificate directly:
```
[Wed Feb 10 18:57:13 UTC 2021] Verifying: iv-test.gauthierplm.me
[Wed Feb 10 18:57:16 UTC 2021] iv-test.gauthierplm.me:Verify error:Fetching http://iv-test.gauthierplm.me/.well-known/acme-challenge/VpsO-SSYJkZpX-H2py8tvIpFQSa6V7CLRBS15CWLUwI: Connection refused
[Wed Feb 10 18:57:16 UTC 2021] Please add '--debug' or '--log' to check more details.
[Wed Feb 10 18:57:16 UTC 2021] See: https://github.com/acmesh-official/acme.sh/wiki/How-to-debug-acme.sh
Successfully installed Let's Encrypt SSL certificates for Invidious
ln: failed to create symbolic link '/usr/local/bin/acme.sh': File exists
done!
```

Also it seems the install of the VHost fails as .well-known does not exists (and error is not reported):
```
mkdir: cannot create directory ‘/etc/nginx/html/.well-known/acme-challenge’: No such file or directory
nginx: [emerg] cannot load certificate "/etc/acme/certs/iv-test.gauthierplm.me/fullchain.pem": BIO_new_file() failed (SSL: error:02001002:system library:fopen:No such file or directory:fopen('/etc/acme/certs/iv-test.gauthierplm.me/fullchain.pem','r') error:2006D080:BIO routines:BIO_new_file:no such file)
nginx: configuration file /etc/nginx/nginx.conf test failed
Successfully installed nginx vhost /etc/nginx/sites-available/iv-test.gauthierplm.me.conf
```
If I create the folder, the mkdir error disappear but I have the same error (without the mkdir error).

I made sure the domain points to the right server, Nginx works properly.
Here is my Invidious config:
```
channel_threads: 1
feed_threads: 1
db: …
full_refresh: false
https_only: false
external_port: 
check_tables: true
port: 3000
host_binding: 0.0.0.0
domain: iv-test.gauthierplm.me
```

What I would suggest is to combine Nginx VHost isntall and Let's Encrypt certificate generation so:
- the VHost is installed without SSL configuration
- certificate is generated and tested on the domain
- the VHost is updated to include the SSL configuration

**Comment by tmiland** [comment]
Thanks for the debug info @GauthierPLM :+1: 

I'll spin up a droplet to do some testing on my end, and post when I'm done.

**Comment by GauthierPLM** [comment]
If it may help: when I used the script without LE integration, I also had to fix the Nginx config after installing it to run certbot. My steps were:
- Install Nginx from Ubuntu repo
- Install the VHost using Invidious Updated
- Remove the VHost to run certbot (the VHost pointing to missing certificates blocked Nginx from running)
- Request a certificate by following these steps: https://certbot.eff.org/lets-encrypt/ubuntufocal-nginx
- Install the VHost again using Invidious Updated
- Made sure Invidious is properly callable when the call is proxied by Nginx (I think I changed the bind address)

**Comment by tmiland** [comment]
Okay,

Please test the new commit 77526ba

Just follow the steps 1-3. :+1: 

```bash
Select an option [1-10]: 9

   1) Install Nginx
   2) Install Nginx Vhost for Invidious
   3) Install Let's Encrypt SSL certificates

Select an option [1-3]: 3

Do you want to install Let's Encrypt SSL certificates for Invidious? [y/n/q]?y

Your Invidious domain name: invidious.domain.tld

Please enter your admin email for the domain [E.G: admin@invidious.domain.tld]:admin@invidious.domain.tld
Reading package lists... Done
Building dependency tree       
Reading state information... Done
cron is already the newest version (3.0pl1-134+deb10u1).
curl is already the newest version (7.64.0-4+deb10u1).
openssl is already the newest version (1.1.1d-0+deb10u4).
socat is already the newest version (1.7.3.2-2).
0 upgraded, 0 newly installed, 0 to remove and 71 not upgraded.
fatal: destination path 'acme.sh' already exists and is not an empty directory.
[Thu Feb 11 09:42:18 UTC 2021] Installing to /etc/acme
[Thu Feb 11 09:42:18 UTC 2021] Installed to /etc/acme/acme.sh
[Thu Feb 11 09:42:18 UTC 2021] Installing alias to '/root/.zshrc'
[Thu Feb 11 09:42:18 UTC 2021] OK, Close and reopen your terminal to start using acme.sh
[Thu Feb 11 09:42:18 UTC 2021] Installing cron job
12 0 * * * "/etc/acme"/acme.sh --cron --home "/etc/acme" --config-home "/etc/acme/data" > /dev/null
[Thu Feb 11 09:42:18 UTC 2021] Good, bash is found, so change the shebang to use bash as preferred.
[Thu Feb 11 09:42:18 UTC 2021] OK
[Thu Feb 11 09:42:19 UTC 2021] Using CA: https://acme-v02.api.letsencrypt.org/directory
[Thu Feb 11 09:42:19 UTC 2021] Single domain='invidious.domain.tld'
[Thu Feb 11 09:42:19 UTC 2021] Getting domain auth token for each domain
[Thu Feb 11 09:42:22 UTC 2021] Getting webroot for domain='invidious.domain.tld'
[Thu Feb 11 09:42:22 UTC 2021] Verifying: invidious.domain.tld
[Thu Feb 11 09:42:27 UTC 2021] Success
[Thu Feb 11 09:42:27 UTC 2021] Verify finished, start to sign.
[Thu Feb 11 09:42:27 UTC 2021] Lets finalize the order.
[Thu Feb 11 09:42:27 UTC 2021] Le_OrderFinalize='https://acme-v02.api.letsencrypt.org/acme/finalize/112352256/7842305653'
[Thu Feb 11 09:42:28 UTC 2021] Downloading cert.
[Thu Feb 11 09:42:28 UTC 2021] Le_LinkCert='https://acme-v02.api.letsencrypt.org/acme/cert/0419908b20c6447df4d51dd3cb652acef156'
[Thu Feb 11 09:42:30 UTC 2021] Cert success.
-----BEGIN CERTIFICATE-----
MIIFLTCCBBWgAwIBAgISBBmQiyXXXXXXXXXXXXXXXXXXXXXXXXXXX3DQEBCwUA
MDIxCzAJBgNVBAYTAlVTMRYwFAYDVQQKEw1MZXQncyBFbmNyeXB0MQswCQYDVQQD
EwJSMzAeFw0yMTAyMTEwODQyMjdaFw0yMTA1MTIwODQyMjdaMB4xHDAaBgNVBAMT
E3Rlc3QuaW52aWRpb3VzLnR1YmUwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEK
AoIBAQC1oi7AEKuyguobxE13djaU/2LEkKJeAoG3ntLtsPj0CjV+pBe/uOmzDThx
/CqTp18SiA55HtvCIY7umjdk0lmoC2uorOLWPMTpY+BPTtNCARjNNxCxDj10fEbi
vLdr1DhB1xGinpfr4LWKpfJLprhCYthB2n/zWCAtxH9LaPzZ6ojzfGVXq2aTu5l7
Wu1LHLcXhaEY6+mtSvFe/oGZt9mCm/5oedjYKxWXVvVdjs2bDN5tbDiIKXhQ8OYf
hDk1VjLZwvIkabzaZcW+8S4FAQ8x38qZUr6XsvW9HekK7ckqHyjyHyFq8BfzgzhP
c2d1tkSTzanUjnpChQ6yuink+/EVAgMBAAGjggJPMIICSzAOBgNVHQ8BAf8EBAMC
BaAwHQYDVR0lBBYwFAYIKwYBBQUHAwEGCCsGAQUFBwMCMAwGA1UdEwEB/wQCMAAw
HQYDVR0OBBYEFF5JodILi67xeH6YuEyCuCsBZ6lZMB8GA1UdIwQYMBaAFBQusxe3
WFbLrlAJQOYfr52LFMLGMFUGCCsGAQUFBwEBBEkwRzAhBggrBgEFBQcwAYYVaHR0
cDovL3IzLm8ubGVuY3Iub3JnMCIGCCsGAQUFBzAChhZodHRwOi8vcjMuaS5sZW5j
ci5vcmcvMB4GA1UdEQQXMBWCE3Rlc3QuaW52aWRpb3VzLnR1YmUwTAYDVR0gBEUw
QzAIBgZngQwBAgEwNwYLKwYBBAGC3xMBAQEwKDAmBggrBgEFBQcCARYaaHR0cDov
L2Nwcy5sZXRzZW5jcnlwdC5vcmcwggEFBgorBgEEAdZ5AgQCBIH2BIHzAPEAdwB9
PvL4j/+IVWgkwsDKnlKJeSvFDngJfy5ql2iZfiLw1wAAAXeQeG5PAAAEAwBIMEYC
IQCH7FwTfKGIZawuZ07Gctc3BsT4iPdFFFLc1jeABtohawIhAKxRaYd/U8GFgFcX
UkaFsHvZq/XSPswp8kkDi16dbvrIAHYAXNxDkv7mq0VEsV6a1FbmEDf71fpH3KFz
lLJe5vbHDsoAAAF3kHhuLwAABAMARzBFAiBjdqsgPdP4SJp0YpSqdYutB84ZUE7i
BCcyr+k353fOKAIhAL4eZollAxCYR6xnH9F2kae/gLMt45YiOlZHZPMAM2lGMA0G
CSqGSIb3DQEBCwUAA4IBAQB9/Xaa+iYMu6f1cOGTWo/hx2ka4T8inqXza+kGZ1z4
xL90OVh/+36yIoxbMAMllkuqt+z8qQg7nzd9Iv5AsaC726JJ0pu5I/UD9m/GNzy1
vSMdxM9n4VDQvDeK1OYsLkR2ofmRsKBI+aBWuy3gT7q2aW7haj4owuteL4I52AtZ
EuCuPzyd5nsdcgf5Kmd+hu7X4pXwhUsIw+fw1+xuFiDcptgPgr3+cGUwzEMV5xu5
ZrvnPd4+z/zbufZwR8ZUKdKJmR+1qMWJiwHT7H6qHL1gWpvYIt2IJt2qVlVIkYHo
bo+bJwQwggmZ7YcwpKBeGd5kyYXudsO+AlDGnhn7fjKe
-----END CERTIFICATE-----
[Thu Feb 11 09:42:30 UTC 2021] Your cert is in  /root/.acme.sh/invidious.domain.tld/invidious.domain.tld.cert 
[Thu Feb 11 09:42:30 UTC 2021] Your cert key is in  /root/.acme.sh/invidious.domain.tld/invidious.domain.tld.key 
[Thu Feb 11 09:42:30 UTC 2021] The intermediate CA cert is in  /root/.acme.sh/invidious.domain.tld/ca.cer 
[Thu Feb 11 09:42:30 UTC 2021] And the full chain certs is there:  /root/.acme.sh/invidious.domain.tld/fullchain.cer 
Successfully issued Let's Encrypt SSL certificates for Invidious
[Thu Feb 11 09:42:31 UTC 2021] Installing cert to:/etc/nginx/certs/invidious.domain.tld/invidious.domain.tld.cert
[Thu Feb 11 09:42:31 UTC 2021] Installing key to:/etc/nginx/certs/invidious.domain.tld/invidious.domain.tld.key
[Thu Feb 11 09:42:31 UTC 2021] Installing full chain to:/etc/nginx/certs/invidious.domain.tld/invidious.domain.tld.fullchain
[Thu Feb 11 09:42:31 UTC 2021] Run reload cmd: systemctl reload nginx.service
[Thu Feb 11 09:42:31 UTC 2021] Reload success
done!
```

**Comment by GauthierPLM** [comment]
Both Vhost install and certificate install now work as expected. Thank you! It makes the process much easier :)

If I may add a suggestion: once the certificate as been installed, it might be useful to ask the user if he wants to update Invidious' configuration to set the `external_port` to 443 and define `https_only` to true so they do not have to do it manually.

**Comment by tmiland** [comment]
That's great! My pleasure :)

I've added your suggestion after cert install, please test fe77e97

**Comment by GauthierPLM** [comment]
I did a total reinstall and it worked as expected (including the other issues I reported).
The only issue I found is that I had to restart invidious and then nginx services after installing the certificate and accepting the change on the config.

From your commit, it seems the invidious service is not restarted after config change. But even after doing so, the HTTPS version of my instance did not respond. I did a restart (not reload) on the nginx service and it worked as expected.

So I think a restart of Invidious' service after config is required, and a restart instead of a reload of Nginx (or maybe a reload is missing)?
It does not seem that reload has effect on Nginx. I also did a restart when I did my test before you latest commit because the config was not properly reloaded.

**Comment by tmiland** [comment]
Thanks for testing. :+1: 

Added requested changes to aa51574

**Comment by GauthierPLM** [comment]
Seems good to me. I can't do a full re-install for now, but the changes seems right.

**Comment by tmiland** [comment]
> Seems good to me. I can't do a full re-install for now, but the changes seems right.

Okay. Thanks for all the help! :+1:
