### ISSUE TITLE
Debian 10 error = ✗ unknown distro: ''

### ISSUE THREAD

**Issue by Incognify** [tmiland/Invidious-Updater#57]
**Describe the bug**
The error shown in the title is presented when attempting to install via the "For latest release" method, as well as the, "Or directly" and the, "Repository" installation instructions.

**To Reproduce**
1.Follow the instructions for any of the above cases.
2. Be met with the error in the title.

**Server (please complete the following information):**
cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 10 (buster)"
NAME="Debian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=debian

**Comment by tmiland** [comment]
Hmm, works on my end. 

Do you have the lsb-release package installed?

**Comment by tmiland** [comment]
Please test dba391d

**Comment by Incognify** [comment]
>Do you have the lsb_release package installed?

Ah ha! That was the issue. Installed, re-ran, and I'm listening to music through my invidious install now.

Thanks. I'm closing this.
