### ISSUE TITLE
Can't access instance via public IP after successful install

### ISSUE THREAD

**Issue by orhanmaden** [tmiland/Invidious-Updater#59]
**Describe the bug**
Can't access instance via public IP after successful install

**To Reproduce**
1. Create a Digital Ocean droplet with a Debian 10 x64 instance with 4 GB / 2 CPUs, 80 GB SSD Disk and 4 TB transfer
2. Install curl: `sudo apt install curl -y`
3. Download script: `curl -s https://api.github.com/repos/tmiland/Invidious-Updater/releases/latest | grep "browser_download_url.*sh" | cut -d : -f 2,3 | tr -d \" | wget -qi -`
4. Set permissions: `chmod +x invidious_update.sh`
5. Run script: `./invidious_update.sh`
6. Set advanced options: 
  ![image](https://user-images.githubusercontent.com/3224537/110103980-e0883c80-7da6-11eb-9209-4db435a6eedc.png)
7. Let the script run to success:
  ![image](https://user-images.githubusercontent.com/3224537/110104067-fa298400-7da6-11eb-8be3-e24b56c7add8.png)

**Expected behavior**
Instance is accessible via the IP address. Unfortunately that is not the case:
![image](https://user-images.githubusercontent.com/3224537/110104265-36f57b00-7da7-11eb-96c9-478a6e6c9da8.png)
![image](https://user-images.githubusercontent.com/3224537/110104298-45439700-7da7-11eb-8b6a-8fac9bf000a5.png)

**Screenshots**
Added above

**Desktop (please complete the following information):**
 - OS: Debian 10 x64
 - Browser: Chrome v88.0.4324.190

**Additional info**
The instance is removed to prevent costs

**Comment by tmiland** [comment]
Hello,

seems like port 80 is blocked in your firewall.

**Comment by orhanmaden** [comment]
Thanks for the quick response. I did the following to tackle the potential issue.

Installed `ufw`: ` apt install ufw -y`
Enabled it: `ufw enable`
Allowed traffic through port 80: `ufw allow http`
Checked status: ` ufw status verbose`
Output:
```
Status: active
Logging: on (low)
Default: deny (incoming), allow (outgoing), disabled (routed)
New profiles: skip

To                         Action      From
--                         ------      ----
80/tcp                     ALLOW IN    Anywhere
80/tcp (v6)                ALLOW IN    Anywhere (v6)
```

It it still not accessible from the public IP. Am I missing something?

**Comment by tmiland** [comment]
I haven't tested a setup like this, so i cannot tell unfortunately.

However, you could set it up to run like this:

```bash
✔ branch        : master
✔ domain        : invidious.tube
✔ ip address    : your_droplet_public_ip
✔ port          : 3000
✔ external port : 443
✔ dbname        : invidious
✔ dbpass        : secretpassword
✔ https only    : true

```

Then use option 9 to setup Nginx. Just go through step 1-3. 

It will then serve invidious from port 3000 reverse proxied to port 443 (https) :+1: 

Make sure port 443 is open in your firewall. 

This is how it's expected to be run on a public IP.

**Comment by orhanmaden** [comment]
I tried your suggestion and that didn't work. After fiddling for a day I got it working with the following configuration

![image](https://user-images.githubusercontent.com/3224537/110175561-43f38800-7e02-11eb-9498-71bb35f5632b.png)

And than the channels gave an error. I give up for now

**Comment by tmiland** [comment]
Sorry to hear it didn't work out. 

The channel error is a bug with invidious: https://github.com/iv-org/invidious/issues/1838
