### ISSUE TITLE
Crystal repos need update

### ISSUE THREAD

**Issue by straight-shoota** [tmiland/Invidious-Updater#69]
The bintray repositories are no longer available. Crystal's distribution packages are now hosted
on the Open Build Service, see https://crystal-lang.org/2021/04/30/new-apt-and-rpm-repositories.html

/cc https://github.com/crystal-lang/crystal-website/pull/138

**Comment by tmiland** [comment]
Depends on https://github.com/iv-org/invidious/issues/1933#issuecomment-816446368

`Only the latest stable release Crystal 1.0.0 is available in the new package repositories. Thus the --channel flag on the installation script is currently ignored, and --crystal only allows the values latest and 1.0.0 (with identical semantics). Nightly builds and unstable releases will be available in the future.`

**Comment by Perflyst** [comment]
Just in case the bintray binaries are gone before Invidious is updated, you can get the old deb package / binary from https://github.com/crystal-lang/crystal/releases/tag/0.36.1

**Comment by markozajc** [comment]
This has now been resolved by the Crystal team: https://crystal-lang.org/2021/04/30/new-apt-and-rpm-repositories.html

**Comment by syeopite** [comment]
Invidious now has support for Crystal 1.0 with iv-org/Invidious#2115

**Comment by controlfreakstudio** [comment]
how do you make this work non-docker? fails on crystal every time. tried installing crystal first, no joy. do you need to have some sort of config altered for an install via invidious-updater to work?

**Comment by tmiland** [comment]
Use Master. Haven't added the fix to any release yet.

**Comment by controlfreakstudio** [comment]
usng master:

./invidious_update.sh: line 1559: shards: command not found
./invidious_update.sh: line 1560: crystal: command not found

✗ [ERROR] Build Process Failed!

 This is most likely an issue with Invidious, not this script!
