### ISSUE TITLE
Updater isn't updating invidious

### ISSUE THREAD

**Issue by RiversideRocks** [tmiland/Invidious-Updater#70]
**Describe the bug**
I ran the update operation from the updater. The script pulls from github and rebuilds, but doesn't update invidious. After trying again the script says invidious is updated, but it seems it is running a version back from May 26th.

**To Reproduce**
1. Run the invidious installer
2. Select 2
3. Install
4. Check api/v1/stats route

**Expected behavior**
Instance should be updated to latest version (I believe it is 2021.06.14-3146678 as of this writing).

**Screenshots**
https://user-images.githubusercontent.com/59586759/122412948-01d6f800-cf54-11eb-8e56-5de67fcff975.mp4

Server OS: Linux Ubuntu 20.04

**Comment by RiversideRocks** [comment]
How would I do that? Would rebuilding wipe all data?

**Comment by tmiland** [comment]
No, not wiping anything. It just rebuilds the updated data from the repo.

It should do that with the update function, but for some reason it didn't is my guess.

**Comment by RiversideRocks** [comment]
I tried updating, still no luck.

**Comment by tmiland** [comment]
Rebuilding after updating should give you the latest version.

If that doesn't work, try uninstalling then installing again.

**Comment by RiversideRocks** [comment]
Just uninstalled and now its saying it wont reinstall 😭

**Comment by RiversideRocks** [comment]
It turns out that my version of crystal wasn't up to date so the whole thing wasn't updating. I would love it if you added prerequisite checking to the script, ie. PostgreSQL, Crystal, etc.
