### ISSUE TITLE
Unable to run Invidious

### ISSUE THREAD

**Issue by balasratran** [tmiland/Invidious-Updater#73]
I have installed successfully but check netstat not invidious. Anyone have a way to fix this please guide me.
![screenshot_1634188169](https://user-images.githubusercontent.com/26430195/137255667-cf900e0d-0723-4175-acad-f4bd47f52400.png)
![screenshot_1634188189](https://user-images.githubusercontent.com/26430195/137255678-d88cc60e-3852-4584-a096-0b090cd4f285.png)

**Comment by tmiland** [comment]
Feel free to re-open if this is still an issue.
