### ISSUE TITLE
Latest release is broken

### ISSUE THREAD

**Issue by TheFrenchGhosty** [tmiland/Invidious-Updater#78]
**Describe the bug**

The latest release is using the bintray report to get the .deb, however it has been deprecated, and it's now broken, and 502

https://github.com/tmiland/Invidious-Updater/blob/v1.5.9/invidious_update.sh#L1064

master is properly updated, so a new release just has to be pushed.

**To Reproduce**

Follow the instruction in the readme that ask users to download the latest release

**Expected behavior**

Release is updated

**Screenshots**

![bug](https://user-images.githubusercontent.com/47571719/148549651-dc404d23-8d18-42b6-be00-d6ee163a0e15.png)

**Desktop (please complete the following information):**

Debian

**Additional context**

An user had this issue.

**Comment by tmiland** [comment]
Howdy,

that should be fixed in Master https://github.com/tmiland/Invidious-Updater/blob/fea1c06aa786dcdbae1bcd087b76a7cf0ba39e8f/invidious_update.sh#L1072-L1091

So use that for now.

```
$ wget https://github.com/tmiland/Invidious-Updater/raw/master/invidious_update.sh
$ chmod +x invidious_update.sh
$ ./invidious_update.sh
```

**Comment by TheFrenchGhosty** [comment]
>that should be fixed in Master 

It is, this is how  we ended up telling the user to use, but the release

**Comment by tmiland** [comment]
Right, added a new [release](https://github.com/tmiland/Invidious-Updater/releases/tag/v1.6.0) just now.

**Comment by TheFrenchGhosty** [comment]
@tmiland Amazing, thanks!
