### ISSUE TITLE
Failed to fetch Crystal

### ISSUE THREAD

**Issue by poltrian** [tmiland/Invidious-Updater#79]
Failed to fetch https://dl.bintray.com/crystal/deb/dists/all/InRelease  502  Bad Gateway [IP: 52.39.229.247 443]
How can i fix it?

**Comment by tmiland** [comment]
Are you using the latest version?

**Comment by poltrian** [comment]
i guess, i use the repo as in the docu described and installed it today

**Comment by poltrian** [comment]
═════════════════════════════════════════════════╗
 ║                        Invidious Update.sh                        ║
 ║               Automatic update script for Invidious               ║
 ║                      Maintained by @tmiland                       ║
 ║                          version: 1.5.9

**Comment by tmiland** [comment]
Latest is v1.6.0. 

Not released in the repo yet.

**Comment by poltrian** [comment]
i downöoad  1.6 but it also not work. Please check the url vor cystal-lang. I wrote you an email. Please check it.....

**Comment by tmiland** [comment]
Please provide the log, so it'll be easier to debug.

**Comment by poltrian** [comment]
https://dl.bintray.com/crystal/deb/dists/all/InRelease  has a 502. The crystal repo won't work

**Comment by poltrian** [comment]
https://www.infoq.com/news/2021/02/jfrog-jcenter-bintray-closure/
bintray is closed so the script can not find the crystal-lang and fails. For me, i add another repo and the script works.
