### ISSUE TITLE
My install can only be accessed via my ip

### ISSUE THREAD

**Issue by TurboCheetah** [tmiland/Invidious-Updater#8]
Like the title states, I can only access my instance via the ip I fed the installer (pretty sure it'd work either way though). HTTP only even though I specified HTTPS-only.

OS: Ubuntu 18.04

**Comment by tmiland** [comment]
Hello, thanks for reporting.

Looks like the script was not adding `external_port: 443` to config.yml.

Re-launch the updater to get the latest release which fixes the problem. 

Note that if `https_only: true` it will add `external_port: 443` which implies you are going to use the instance with a reverse proxy, where SSL will be set up for HTTPS. 

The instance will still work accessing the ip with HTTP.
