### ISSUE TITLE
Error: Undefined method 'starts_with?' for Array(String) (compile-time type is (Array(String) | Bool | Float64 | Int32 | Int64 | Invidious::User | Preferences | String))

### ISSUE THREAD

**Issue by kernelcrunch** [tmiland/Invidious-Updater#82]
Upon running an update (Option 2), I ran into the error below.  Invidious ultimately started in the end.  Let me know if you need additional information (and how to pull it).  This is running on Ubuntu 20.04, 6GB RAM, 8 Cores.

...Using athena-negotiation (0.1.1)
Using spectator (0.10.5
Using ameba (0.14.3)

**Checking player dependencies...
Player dependencies are satisfied
Showing last frame. Use --error-trace for full trace.

In src/invidious/routes/playlists.cr:227:23

 227 | if !plid || !plid.starts_with?("IV")
                         ^-----------
Error: undefined method 'starts_with?' for Array(String) (compile-time type is (Array(String) | Bool | Float64 | Int32 | Int64 | Invidious::User | Preferences | String))
/home/invidious/invidious

✔ Done Rebuilding /home/invidious/invidious 

-- restarting Invidious
● invidious.service - Invidious (An alternative YouTube front-end)
     Loaded: loaded (/lib/systemd/system/invidious.service; enabled; vendor preset: enabled)
     Active: active (running) since Thu 2022-02-24 15:24:15 CST; 2s ago
   Main PID: 5272 (invidious)
      Tasks: 8 (limit: 6996)
     Memory: 34.1M
     CGroup: /system.slice/invidious.service
             └─5272 /home/invidious/invidious/invidious -o invidious.lo

**Comment by SamantazFox** [comment]
Please see issue https://github.com/iv-org/invidious/issues/2918 (over on the invidious repo) and #81 (PR for fixing invidious updater).

**Comment by tmiland** [comment]
Should be fixed in [v1.6.1](https://github.com/tmiland/Invidious-Updater/releases/tag/v1.6.1)
