### ISSUE TITLE
shard.lock is modified during update, causing error during compilation

### ISSUE THREAD

**Issue by GauthierPLM** [tmiland/Invidious-Updater#83]
Every time I use invidious_updater to update invidious, the update fails with the following error:

```
Checking player dependencies...
Player dependencies are satisfied
Showing last frame. Use --error-trace for full trace.

In src/invidious/routes/playlists.cr:227:23

 227 | if !plid || !plid.starts_with?("IV")
                         ^-----------
Error: undefined method 'starts_with?' for Array(String) (compile-time type is (Array(String) | Bool | Float64 | Int32 | Int64 | Invidious::User | Preferences | String))
/home/invidious/invidious
```

When checking in the git repository, I noticed that the `shard.lock` file is modified during the update process, resulting in the following diff:

```diff
diff --git a/shard.lock b/shard.lock
index be4333c1..5482d75a 100644
--- a/shard.lock
+++ b/shard.lock
@@ -1,5 +1,9 @@
 version: 2.0
 shards:
+  ameba:
+    git: https://github.com/crystal-ameba/ameba.git
+    version: 0.14.3
+
   athena-negotiation:
     git: https://github.com/athena-framework/negotiation.git
     version: 0.1.1
@@ -14,15 +18,11 @@ shards:

   exception_page:
     git: https://github.com/crystal-loot/exception_page.git
-    version: 0.2.0
+    version: 0.2.2

   kemal:
     git: https://github.com/kemalcr/kemal.git
-    version: 1.1.0
-
-  kilt:
-    git: https://github.com/jeromegn/kilt.git
-    version: 0.6.1
+    version: 1.1.2

   lsquic:
     git: https://github.com/iv-org/lsquic.cr.git
@@ -42,12 +42,9 @@ shards:

   spectator:
     git: https://github.com/icy-arctic-fox/spectator.git
-    version: 0.10.4
+    version: 0.10.5

   sqlite3:
     git: https://github.com/crystal-lang/crystal-sqlite3.git
     version: 0.18.0

-  ameba:
-    git: https://github.com/crystal-ameba/ameba.git
-    version: 0.14.3
```

I could not find the root cause of this issue by looking at the shell file, so I open this issue, hoping you might find the issue.
This is the steps to reproduce the issue:
- Start with a repository without any modification (git status should not mention any modified file / log files do not impact the process).
- `git reset --hard f4e19ac05c33f0a0995fe9cbb7678cd0b90a3149` (3 commit behind current master)
- Launch invidious_updater (version: 1.5.9)
- Update invidious
- The update with fail with the error message above

I could consistently reproduce this issue for a couple of months now and had to build invidious by myself since then.

**Comment by tmiland** [comment]
Have you tried latest version? (v1.6.1)

**Comment by GauthierPLM** [comment]
Ah, it seems I missed some release : I followed the instructions in the [Repository section](https://github.com/tmiland/Invidious-Updater#repository) of the Readme, but it seems the repo is down.

I will install it manually.

**Comment by tmiland** [comment]
Sorry about that. Haven't added the last two updates to the repo yet.

**Comment by GauthierPLM** [comment]
I confirm it works as expected! Sorry for not using the latest version of the script.
