### ISSUE TITLE
Unable to install (error)

### ISSUE THREAD

**Issue by Quuinnn** [tmiland/Invidious-Updater#84]
**Describe the bug**
```fatal: unsafe repository ('/home/invidious/invidious' is owned by someone else)
To add an exception for this directory, call:

        git config --global --add safe.directory /home/invidious/invidious
fatal: unsafe repository ('/home/invidious/invidious' is owned by someone else)
To add an exception for this directory, call:

        git config --global --add safe.directory /home/invidious/invidious
Showing last frame. Use --error-trace for full trace.

In src/invidious.cr:68:25

 68 | CURRENT_COMMIT  = {{ "#{`git rev-list HEAD --max-count=1 --abbrev-commit`.strip}" }}
                              ^
Error: error executing command: git rev-list HEAD --max-count=1 --abbrev-commit, got exit status 128

✗ [ERROR] Build Process Failed!

 This is most likely an issue with Invidious, not this script!
```
**Desktop (please complete the following information):**
 - OS: Arch Linux

**Comment by tmiland** [comment]
Could you run `./invidious_update.sh 2>&1 | tee invidious_update.log` and attach the `invidious_update.log`?

**Comment by Quuinnn** [comment]
sure,
https://pastebin.com/aA1tLaxf

**Comment by tmiland** [comment]
> sure, https://pastebin.com/aA1tLaxf

Thanks. Looking into this now.

**Comment by tmiland** [comment]
Try the latest release @Quuinnn

**Comment by Quuinnn** [comment]
the db error seems to be fixed, but there still is some sought of error
https://pastebin.com/xGHWZkmN
here is the log

**Comment by tmiland** [comment]
Thanks.
I did tests on Manjaro Linux, the Arch install was lost so was unable to test.
Going to try and set up a new Arch installation for testing and report back once testing is done. :+1:

**Comment by Quuinnn** [comment]
thanks for the efforts :)

**Comment by tmiland** [comment]
Okay, try to re-download the latest version @Quuinnn

**Comment by Quuinnn** [comment]
there is progress,
i chose the basic install without the advanced options.

crystal was able to build invidious src and i got a success message from the script,
although when i try to reach the port, localhost:3000, it says cant connect

https://pastebin.com/mmZ5m9vS -> full log

![image](https://user-images.githubusercontent.com/103880869/166145882-90ef57db-4709-406c-a939-9ec371e862b2.png)

**Comment by Quuinnn** [comment]
i checked the journalctl of the invidious service using -u flag,
and in the logs it says
> May 01 18:15:31 celestia invidious[49357]: [production] Invidious is ready to lead at http://[::1]:3000
it seems to be running on a different hostname
but when i run manually, it works fine with localhost

**Comment by tmiland** [comment]
Great! So it's working. :+1: 

Seems it wants to run on IPv6 and not IPv4, which seems weird. Never encountered that. 

Default setup is `localhost`, so you could try the advanced option and set the ipv4 manually.

**Comment by SamantazFox** [comment]
> it seems to be running on a different hostname but when i run manually, it works fine with localhost

For you information, `[::1]` is the equivalent of `127.0.0.1` in IPv6 :)

`localhost` resolves to either one of those (or both) depending on system configuration. If you want to know more, check `/etc/hosts`.

**Comment by Quuinnn** [comment]
> 

oh, i didnt know that,
thanks for the info!

**Comment by Quuinnn** [comment]
thanks for the help @tmiland
