### ISSUE TITLE
psql: FATAL: Peer authentication failed for user "kemal"

### ISSUE THREAD

**Issue by arvidortwig** [tmiland/Invidious-Updater#85]
When running the script (download and execute) to install invidious it throws the error: 
psql: FATAL: Peer authentication failed for user "kemal"

**Expected behavior**
➜ Running /home/invidious/invidious/config/sql/users.sql
CREATE TABLE
GRANT
CREATE INDEX

Running on Debian 11

Solution: 
Add -h 127.0.0.1 to the command in line 1598:
 ${SUDO} -i -u postgres PGPASSWORD="$PSQLPASS" psql -U kemal -h 127.0.0.1 -d $PSQLDB -f $file

**Comment by tmiland** [comment]
Closing.
Not able to reproduce this issue on Debian 11 with latest [Master](https://raw.githubusercontent.com/tmiland/Invidious-Updater/master/invidious_update.sh)
