### ISSUE TITLE
Error: error executing command: git rev-list HEAD --max-count=1 --abbrev-commit, got exit status 128

### ISSUE THREAD

**Issue by sushidog992** [tmiland/Invidious-Updater#90]
This bug occurs when installing Invidious-Updater on Ubuntu 22

Downloaded using: 
```
curl -s https://api.github.com/repos/tmiland/Invidious-Updater/releases/latest \
| grep "browser_download_url.*sh" \
| cut -d : -f 2,3 \
| tr -d \" \
| wget -qi -

```
```
sudo chmod +x invidious_update.sh
sudo ./invidious_update.sh
```

Then chose option 1 to install invidious.

Error is as follows: 

Invidious is ready to be installed, press any key to continue...

Hit:1 http://us.archive.ubuntu.com/ubuntu jammy InRelease
Get:2 http://us.archive.ubuntu.com/ubuntu jammy-updates InRelease [114 kB]     
Ign:3 https://download.docker.com/linux/debian jammy InRelease                 
Get:4 http://security.ubuntu.com/ubuntu jammy-security InRelease [110 kB]      
Hit:5 https://download.docker.com/linux/ubuntu jammy InRelease                 
Err:7 https://download.docker.com/linux/debian jammy Release                   
  404  Not Found [IP: 2600:9000:2366:9800:3:db06:4200:93a1 443]
Get:8 http://us.archive.ubuntu.com/ubuntu jammy-backports InRelease [99.8 kB]  
Hit:6 https://deb.librewolf.net jammy InRelease                                
Reading package lists... Done                    
E: The repository 'https://download.docker.com/linux/debian jammy Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
➜ Downloading Invidious from GitHub
Cloning into 'invidious'...
remote: Enumerating objects: 23195, done.
remote: Counting objects: 100% (36/36), done.
remote: Compressing objects: 100% (26/26), done.
remote: Total 23195 (delta 12), reused 27 (delta 10), pack-reused 23159
Receiving objects: 100% (23195/23195), 21.88 MiB | 2.87 MiB/s, done.
Resolving deltas: 100% (15441/15441), done.
channel_threads: 1
feed_threads: 1
db:
  user: kemal
  password: kemal
  host: localhost
  port: 5432
  dbname: invidious
full_refresh: false
https_only: false
domain:
fatal: detected dubious ownership in repository at '/home/invidious/invidious'
To add an exception for this directory, call:

	git config --global --add safe.directory /home/invidious/invidious
➜ Done
/home/invidious
Synchronizing state of postgresql.service with SysV service script with /lib/systemd/systemd-sysv-install.
Executing: /lib/systemd/systemd-sysv-install enable postgresql
➜ Creating user kemal with password VwJILfTDAJR7R04KagjeQ7WHzom8BL7K 
CREATE ROLE
➜ Creating database invidious with owner kemal
CREATE DATABASE
➜ Grant all on database invidious to user kemal
GRANT
➜ Running /home/invidious/invidious/config/sql/annotations.sql 
CREATE TABLE
GRANT
➜ Running /home/invidious/invidious/config/sql/channels.sql 
CREATE TABLE
GRANT
CREATE INDEX
➜ Running /home/invidious/invidious/config/sql/channel_videos.sql 
CREATE TABLE
GRANT
CREATE INDEX
➜ Running /home/invidious/invidious/config/sql/nonces.sql 
CREATE TABLE
GRANT
CREATE INDEX
➜ Running /home/invidious/invidious/config/sql/playlists.sql 
CREATE TYPE
CREATE TABLE
GRANT
➜ Running /home/invidious/invidious/config/sql/playlist_videos.sql 
CREATE TABLE
GRANT
➜ Running /home/invidious/invidious/config/sql/session_ids.sql 
CREATE TABLE
GRANT
CREATE INDEX
➜ Running /home/invidious/invidious/config/sql/users.sql 
CREATE TABLE
GRANT
CREATE INDEX
➜ Running /home/invidious/invidious/config/sql/videos.sql 
CREATE TABLE
GRANT
CREATE INDEX
✔ Finished Database section
➜ Updating config.yml with new info...
✔ Done.
Resolving dependencies
Fetching https://github.com/kemalcr/kemal.git
Fetching https://github.com/iv-org/protodec.git
Fetching https://github.com/jeromegn/kilt.git
Fetching https://github.com/iv-org/lsquic.cr.git
Fetching https://github.com/will/crystal-pg.git
Fetching https://github.com/athena-framework/negotiation.git
Fetching https://github.com/crystal-lang/crystal-sqlite3.git
Fetching https://github.com/crystal-lang/crystal-db.git
Fetching https://github.com/luislavena/radix.git
Fetching https://github.com/crystal-loot/exception_page.git
Fetching https://github.com/sija/backtracer.cr.git
Installing db (0.10.1)
Installing pg (0.24.0)
Installing sqlite3 (0.18.0)
Installing radix (0.4.1)
Installing backtracer (1.2.1)
Installing exception_page (0.2.2)
Installing kemal (1.1.2)
Installing kilt (0.6.1)
Installing protodec (0.1.4)
Installing lsquic (2.18.1-2)
Installing athena-negotiation (0.1.1)

Checking player dependencies, this may take more than 20 minutes... If it is stuck, check your internet connection.
Resolving player dependencies
Fetched videojs-http-source-selector
Fetched videojs-contrib-quality-levels
Fetched videojs-overlay
Fetched videojs-mobile-ui
Fetched videojs-markers
Fetched videojs-vtt-thumbnails
Fetched videojs-share
Fetched video.js
Fetched videojs-vr

Done checking player dependencies, now compiling Invidious...
fatal: detected dubious ownership in repository at '/home/invidious/invidious'
To add an exception for this directory, call:

	git config --global --add safe.directory /home/invidious/invidious
fatal: detected dubious ownership in repository at '/home/invidious/invidious'
To add an exception for this directory, call:

	git config --global --add safe.directory /home/invidious/invidious
Showing last frame. Use --error-trace for full trace.

In src/invidious.cr:68:25

 68 | CURRENT_COMMIT  = {{ "#{`git rev-list HEAD --max-count=1 --abbrev-commit`.strip}" }}
                              ^
Error: error executing command: git rev-list HEAD --max-count=1 --abbrev-commit, got exit status 128

✗ [ERROR] Build Process Failed!

 This is most likely an issue with Invidious, not this script!

➜ Report issue: https://github.com/iv-org/invidious/issues

**Comment by tmiland** [comment]
Please see https://github.com/tmiland/Invidious-Updater/issues/88#issuecomment-1193922977
