### ISSUE TITLE
url listed in the script is incorrect

### ISSUE THREAD

**Issue by KwisatzJim** [tmiland/invidious-updater#96]
**Describe the bug**
when running the script it will say:
Documentation for this script is available here:
➜ https://github.com/tmiland/tmiland/Invidious-Updater

however, the URL given has capital I and U, and has an extra 'tmiland', which gives a 404 error.
the URL should be:
https://github.com/tmiland/invidious-updater

**To Reproduce**
1. Run the Invidious Updater script: $ ./invidious_update.sh
2. type in password
3. See incorrect URL

**Expected behavior**
show correct URL

**Screenshots**
![Screenshot 2023-01-15 at 7 37 18 AM](https://user-images.githubusercontent.com/131250/212545043-eef8e560-568a-4d86-8d32-6113b86b3952.jpg)

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04.5 LTS x86_64
 - Browser Firefox
 - Version 108.02

**Additional context**

**Comment by tmiland** [comment]
Thanks for reporting!

**Comment by KwisatzJim** [comment]
I forgot to mark one other thing in the screenshot that is in the writeup...

 ➜ https://github.com/tmiland/tmiland/invidious-updater

should be
 ➜ https://github.com/tmiland/invidious-updater
